apiVersion: v1
kind: Service
metadata:
  name: terraform_backend
  labels:
    app: terraform_backend
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:    
    app: terraform_backend
  type: NodePort